"""Ensure username and role are in User model

Revision ID: 048f529864fc
Revises: 212ef42e8a31
Create Date: 2025-06-26 18:14:11.115891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048f529864fc'
down_revision = '212ef42e8a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
