"""Add filename columns to tests table

Revision ID: 0a786878c640
Revises: bdbfc0d501da
Create Date: 2025-08-07 16:52:06.469279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a786878c640'
down_revision = 'bdbfc0d501da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_paper_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('rubric_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('marking_guide_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('answered_script_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('class_list_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('combined_scripts_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('question_paper_path')
        batch_op.drop_column('class_list_path')
        batch_op.drop_column('combined_scripts_path')
        batch_op.drop_column('presence_csv_path')
        batch_op.drop_column('rubric_path')
        batch_op.drop_column('answered_script_path')
        batch_op.drop_column('attendance_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('answered_script_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rubric_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('presence_csv_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('combined_scripts_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('class_list_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('question_paper_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('combined_scripts_filename')
        batch_op.drop_column('class_list_filename')
        batch_op.drop_column('answered_script_filename')
        batch_op.drop_column('marking_guide_filename')
        batch_op.drop_column('rubric_filename')
        batch_op.drop_column('question_paper_filename')

    # ### end Alembic commands ###
