"""Add combined_scripts_path to Test

Revision ID: 178f57450f52
Revises: 6df7a2d51569
Create Date: 2025-08-03 01:54:37.956325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178f57450f52'
down_revision = '6df7a2d51569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
