"""Consistent Integer Foreign Keys

Revision ID: 2fc2c8c491d7
Revises: 4bafa382ab60
Create Date: 2025-07-23 02:49:54.735189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fc2c8c491d7'
down_revision = '4bafa382ab60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['ocr_submission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('audit_log')
    op.drop_table('submission_files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('marked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('submission_files_student_id_fkey')),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], name=op.f('submission_files_test_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('submission_files_pkey'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('old_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['ocr_submission.id'], name=op.f('audit_log_ocr_submission_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('audit_log_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
