"""Add is_locked column to Test

Revision ID: 3673c1c8e5ec
Revises: 90eb7e0ec94f
Create Date: 2025-07-23 16:45:09.372071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3673c1c8e5ec'
down_revision = '90eb7e0ec94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('is_locked')

    # ### end Alembic commands ###
