"""Add student_scripts_path to Test model

Revision ID: 6df7a2d51569
Revises: 81c1b97ac9cf
Create Date: 2025-08-02 20:39:06.277388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df7a2d51569'
down_revision = '81c1b97ac9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_submission_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ocr_submission', ['ocr_submission_id'], ['id'])

    with op.batch_alter_table('page_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tests', ['test_id'], ['id'])

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_scripts_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('student_scripts_path')

    with op.batch_alter_table('page_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('test_id')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ocr_submission_id')

    # ### end Alembic commands ###
