"""Add test_id to StudentSubmission

Revision ID: 7336e6c2d860
Revises: bfcfe63e9486
Create Date: 2025-07-19 20:27:38.867704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7336e6c2d860'
down_revision = 'bfcfe63e9486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_guide', schema=None) as batch_op:
        batch_op.drop_column('rubric_filename')

    with op.batch_alter_table('student_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'test', ['test_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('test_id')

    with op.batch_alter_table('marking_guide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubric_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
