"""Add rubric_filename to MarkingGuide

Revision ID: 8103af697c0f
Revises: 3e0a3505bd48
Create Date: 2025-07-21 19:43:54.939489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8103af697c0f'
down_revision = '3e0a3505bd48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_guide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubric_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_guide', schema=None) as batch_op:
        batch_op.drop_column('rubric_filename')

    # ### end Alembic commands ###
