"""Add new file path columns to Test model

Revision ID: 901758acb80f
Revises: 178f57450f52
Create Date: 2025-08-03 02:38:02.991886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901758acb80f'
down_revision = '178f57450f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_pdf_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('rubric_pdf_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('answer_key_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('combined_scripts_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('combined_scripts_path')
        batch_op.drop_column('answer_key_path')
        batch_op.drop_column('rubric_pdf_path')
        batch_op.drop_column('test_pdf_path')

    # ### end Alembic commands ###
