"""empty message

Revision ID: 90eb7e0ec94f
Revises: 2fc2c8c491d7
Create Date: 2025-07-23 15:09:27.840016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90eb7e0ec94f'
down_revision = '2fc2c8c491d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_student_script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=128), nullable=True),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('page_range', sa.String(length=32), nullable=True),
    sa.Column('script_path', sa.String(length=256), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracted_student_script')
    # ### end Alembic commands ###
