"""Add new stuff

Revision ID: 94d789abf61a
Revises: 23a241503621
Create Date: 2025-07-30 20:38:36.720141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94d789abf61a'
down_revision = '23a241503621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('user')
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.alter_column('student_ids_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.alter_column('student_ids_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('registered_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name='user_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('grade_level', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('guide_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rubric_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('exam_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answered_script_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('question_paper_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_ids_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('attendance_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('presence_csv_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], name=op.f('test_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_pkey'))
    )
    # ### end Alembic commands ###
