"""Add created_at to Test model

Revision ID: 9ea5e3ec8f02
Revises: 1669f591985d
Create Date: 2025-07-21 18:28:37.933328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea5e3ec8f02'
down_revision = '1669f591985d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
