"""Add grade_level to MarkingGuide

Revision ID: af2e72e1277c
Revises: 3e007b842e55
Create Date: 2025-07-03 00:36:08.339888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2e72e1277c'
down_revision = '3e007b842e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_guide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_level', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_guide', schema=None) as batch_op:
        batch_op.drop_column('grade_level')

    # ### end Alembic commands ###
