"""Rename metadata to override_metadata

Revision ID: bdbfc0d501da
Revises: cddd236376fe
Create Date: 2025-08-06 13:03:31.808801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbfc0d501da'
down_revision = 'cddd236376fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_override_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('override_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('previous_value', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('new_value', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('override_metadata', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pdf_path',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('answer_key_path')
        batch_op.drop_column('guide_path')
        batch_op.drop_column('test_pdf_path')
        batch_op.drop_column('rubric_pdf_path')
        batch_op.drop_column('student_scripts_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_scripts_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rubric_pdf_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test_pdf_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('guide_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('answer_key_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('ocr_override_logs', schema=None) as batch_op:
        batch_op.alter_column('pdf_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('override_metadata')
        batch_op.drop_column('new_value')
        batch_op.drop_column('previous_value')
        batch_op.drop_column('override_type')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
