"""Add upload_date to MarkingGuide

Revision ID: c3f0129da86a
Revises: 048f529864fc
Create Date: 2025-06-30 05:33:22.253572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f0129da86a'
down_revision = '048f529864fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_guide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_guide', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###
