"""Add answered_script_filename to MarkingGuide

Revision ID: c637d528c20a
Revises: 8103af697c0f
Create Date: 2025-07-21 19:53:04.345241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c637d528c20a'
down_revision = '8103af697c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_guide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answered_script_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marking_guide', schema=None) as batch_op:
        batch_op.drop_column('answered_script_filename')

    # ### end Alembic commands ###
