"""Add exam_date to Test

Revision ID: cee7a168785b
Revises: 3673c1c8e5ec
Create Date: 2025-07-23 22:59:59.615228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee7a168785b'
down_revision = '3673c1c8e5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('exam_date')

    # ### end Alembic commands ###
